spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

jwt:
  secret: ${jwt.secret}
  expire-time:
    access-token: ${jwt.expire-time.access-token}
    refresh-token: ${jwt.expire-time.refresh-token}

imp:
  api:
    key: ${imp.api.key}
    secret-key: ${imp.api.secret-key}

sms:
  api-key: ${sms.api-key}
  api-secret: ${sms.api-secret}
  sender: ${sms.sender}
  provider: https://api.coolsms.co.kr

app:
  local-url: ${app.local-url}
  prod-url: ${app.prod-url}

cloud:
  aws:
    credentials:
      accessKey: ${cloud.aws.credentials.accessKey}
      secretKey: ${cloud.aws.credentials.secretKey}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: false
  s3:
    bucket: ${cloud.s3.bucket}